# Exceptions

Exceptions are expressions in Scala. we can state the below expression which will crash our programme.

```
val aWeirdValue: String = throw new NullPointerException
```

throwable classes extend the throwable class. There are two major sub types of throwable.

1. Exceptions
2. Errors

Example of throwing exception

```
   def getInt(withExceptions: Boolean) : Int =
     if(withExceptions) throw new RuntimeException("No int for you")
     else 42
```

Typically we wiill write an exception within a try, catch, finally block

1. try = code we will try to run
2. catch = code that will catch errors
3. finally = optional block, does not influece the return type, will run no matter what. Primary used for side effects.

```
 val potenialFail = try {
    getInt(true)
  } catch {
        case e: RuntimeException => println("caught a runtime exception")
      } finally {
    println("Finally")
  }
```

### Defining our own exceptions

we just extend the exception class

```
  class MyException extends Exception
  val myCustomException = new MyException
  throw myCustomException
```

### Example

```
class OverflowException extends RuntimeException
  class UnderFlowException extends RuntimeException
 object PocketCalculator{
  def add(x: Int, y: Int) = {
    val result = x+y
    if(x > 0 && y >0 && result < 0) throw new OverflowException
    else if (x <0 && y <0 && result > 0) throw new UnderFlowException
    else result
  }

   def subtract(x: Int, y:Int) = {
     val result = x-y
     if(x > 0 && y <0 && result < 0) throw new OverflowException
     else if (x <0 && y > 0 && result > 0) throw new UnderFlowException
     else result
   }
```

## Summary

Exceptions crash your programme
Throwing exceptions return nothing
We use thr above structure to throw exceptions with the try catch and the if else,
We can define our own Exceptions with use of extensions.
